### ISSUE TITLE
Add offline maps server to air-gapped.yml

### ISSUE THREAD

**Issue by jonwelch28323** [Xzeryn/Elastic-Stack-Docker#20]
maps:
    depends_on:
      es01:
        condition: service_healthy
    image: docker.elastic.co/elastic-maps-service/elastic-maps-server-ubi8:8.14.3
    container_name: maps
    restart: always
    ports:
      - 8088:8080
    volumes:
      - certs:/usr/src/app/server/certs
      - certs:/etc/ssl/certs
      - ./config/elastic-maps-server.yml:/usr/src/app/server/config/elastic-maps-server.yml
      - ./maps/planet.mbtiles:/usr/src/app/data/planet.mbtiles

**Comment by allamiro** [comment]
@jonwelch28323 

Hey, I fixed the indentation. If you're not planning on making a pull request, I'll gladly add it to my fork.  Just giving you a heads up! 😄

```
maps:
  image: docker.elastic.co/elastic-maps-service/elastic-maps-server-ubi8:8.14.3
  container_name: maps
  restart: always
  ports:
    - 8088:8080
  volumes:
    - certs:/usr/src/app/server/certs
    - certs:/etc/ssl/certs
    - ./config/elastic-maps-server.yml:/usr/src/app/server/config/elastic-maps-server.yml
    - ./maps/planet.mbtiles:/usr/src/app/data/planet.mbtiles
   ```
